// This file will be auto-generated by `npm run supabase:types` once your
// Supabase project is set up and migrations have been applied. For now we
// hand-stub just enough surface area to keep the M0 client code well-typed.
//
// Replace this file by running:
//   npm run supabase:types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

interface UsersRow {
  id: string;
  display_name: string | null;
  avatar_url: string | null;
  couple_id: string | null;
  birthday: string | null;
  timezone: string;
  created_at: string;
  updated_at: string;
}

interface CouplesRow {
  id: string;
  owner_id: string;
  partner_id: string | null;
  anniversary: string | null;
  unbinding_at: string | null;
  theme_preset: string | null;
  created_at: string;
  updated_at: string;
}

type Insertable<T> = Partial<T>;
type Updatable<T> = Partial<T>;

export type Database = {
  public: {
    Tables: {
      users: {
        Row: UsersRow;
        Insert: Insertable<UsersRow>;
        Update: Updatable<UsersRow>;
        Relationships: [];
      };
      couples: {
        Row: CouplesRow;
        Insert: Insertable<CouplesRow>;
        Update: Updatable<CouplesRow>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      generate_invite_code: {
        Args: Record<string, never>;
        Returns: { code: string; expires_at: string }[];
      };
      redeem_invite_code: {
        Args: { p_code: string };
        Returns: { couple_id: string }[];
      };
      current_user_couple_id: {
        Args: Record<string, never>;
        Returns: string | null;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
